Add terms for VBE and MBE
magento/glossary pull request #40
Opened 2020-09-01 16:48 UTC by shrielenee

## Scope of this PR

- New Topic: Adds terms

## Purpose of this PR (required)

The purpose of this PR is to add MBE and VBE terms to the glossary.

## Affected Terms (required)

- magento-bundled-extension.md
- vendor-bundled-extension.md

## Links to source code (remove if unused)

If this PR references a file in a Magento codebase repository, add it here.

- ...
- ...

2020-09-01 18:04 UTC, jeff-matthews requested changes

2020-09-01 18:04 UTC, jeff-matthews commented on src/terms/vendor-bundled-extension.md
> +Vendor-produced code that extends or customizes Magento behavior and operates as a third-party extension is considered a Vendor Bundled Extension (VBE). VBEs are thoroughly tested and included with e
```suggestion
Vendor-produced code that extends or customizes Magento behavior and operates as a third-party extension is considered a Vendor Bundled Extension (VBE). VBEs are thoroughly tested and included with each supported version of Magento Open Source and Magento Commerce. A Vendor Bundled Extension (VBE) can include modules, themes, and language packs.
```

2020-09-01 18:14 UTC, shrielenee commented on src/terms/vendor-bundled-extension.md
> +Vendor-produced code that extends or customizes Magento behavior and operates as a third-party extension is considered a Vendor Bundled Extension (VBE). VBEs are thoroughly tested and included with e
Whoops! Thanks.

2020-09-01 18:17 UTC, jeff-matthews approved these changes

2020-09-01 21:20 UTC, jcalcaben approved these changes

2020-09-01 21:21 UTC, merged

2020-09-02 13:09 UTC, shrielenee commented
Woooo! Glossary additions!